service:
  name: io-ts-sh-example

package:
  exclude:
    - node_modules/io-ts-serverless-handler/**
    - "!node_modules/io-ts-serverless-handler/lib/**"
    - "!node_modules/io-ts-serverless-handler/es6/**"
    - "!node_modules/io-ts-serverless-handler/package.json"
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: "yarn" # Packager that will be used to package your external modules

# Add the serverless-webpack plugin
plugins:
  - "@kingdarboja/serverless-plugin-typescript"
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  listProducts:
    handler: src/handler.listProducts
    events:
      - http:
          method: get
          path: products
  getProduct:
    handler: src/handler.getProduct
    events:
      - http:
          method: get
          path: products/{id}
