# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      CC_SECRET: ${{ secrets.CC_SECRET }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Skip post-install scripts here, as a malicious
      # script could steal NODE_AUTH_TOKEN.
      - run: yarn install --ignore-scripts
      - run: yarn build
      - run: yarn quality-check
        env:
          CI: true
      - run: yarn commitlint --from `git show-ref -s "${GITHUB_REF}"` --to `git show-ref -s "${GITHUB_HEAD_REF}"` --verbose
        if: github.event_name == 'pull_request'
      - run: yarn codechecks
        if: github.event_name != 'pull_request'
      - run: bash <(curl -s https://codecov.io/bash)
      - run: yarn semantic-release
        if: matrix.node-version == '12.x'
